/*
 * 토큰 해석 맵 스냅샷(계획 §2.2 «alias 이행» B-0, #11).
 *
 * 손으로 쓴 CSS 정본을 «이름 → 끝까지 해석한 값» 으로 고정해 둔다. Phase B 가 DTCG JSON + 생성기로 정본을 옮길 때 생성물이 이 맵과
 * 같아야 «소비자 이름은 마지막까지 불변» 이 증명된다(B-2: 생성물 해석 맵 == 스냅샷). 그 전까지는 토큰 값의 변경이 리뷰에 diff 로 보이게 한다.
 *
 * 라이트는 전량이고 다크는 **라이트와 다른 항목만** 적는다 — 다크에서 무엇이 바뀌는지가 그 자체로 계약(크롬만 갈린다)이라 diff 가 문서다.
 */
import { describe, expect, it } from "vitest";

import { loadTokenModel, resolvedMap } from "./model";

const model = loadTokenModel();
const light = resolvedMap(model, "light");
const darkAll = resolvedMap(model, "dark");
const dark = Object.fromEntries(Object.entries(darkAll).filter(([name, value]) => light[name] !== value));

describe("토큰 해석 맵", () => {
  it("모든 토큰이 끝까지 해석된다 — var( 가 남지 않는다", () => {
    const unresolved = Object.entries({ ...light, ...darkAll })
      .filter(([, value]) => value.includes("var("))
      .map(([name, value]) => `${name}: ${value}`);
    expect(unresolved).toEqual([]);
  });

  it("다크에서 갈리는 것은 크롬뿐이다", () => {
    for (const name of Object.keys(dark)) expect(name).toMatch(/^--(?:chrome-|color-)/);
  });

  it("라이트", () => {
    expect(light).toMatchInlineSnapshot(`
      {
        "--animate-in-fade": "fade 0.12s linear",
        "--animate-in-pop": "pop 0.14s cubic-bezier(0.22, 0.8, 0.3, 1)",
        "--animate-in-rise": "rise 0.16s cubic-bezier(0.22, 0.8, 0.3, 1)",
        "--animate-shimmer": "shimmer 1.25s linear infinite",
        "--bg": "#f4f4f4",
        "--black": "#1a1a1a",
        "--canvas-bg": "#ffffff",
        "--canvas-grid": "#ebebeb",
        "--canvas-ink": "#1a1a1a",
        "--canvas-ink-2": "#3a3a3a",
        "--canvas-line": "#dcdcdc",
        "--canvas-line-strong": "#bfbfbf",
        "--canvas-muted": "#6b6b6b",
        "--canvas-plan-bg": "#f4f4f2",
        "--canvas-surface": "#fafafa",
        "--charcoal": "#3a3a3a",
        "--chrome-accent": "#0869e1",
        "--chrome-accent-hover": "#0a5cc4",
        "--chrome-accent-ink": "#ffffff",
        "--chrome-accent-soft": "#eef5fe",
        "--chrome-accent-track": "#e6eff8",
        "--chrome-bg": "#eff1f7",
        "--chrome-danger": "#c2410c",
        "--chrome-danger-soft": "#fbeae3",
        "--chrome-disabled": "#a0a6b4",
        "--chrome-focus": "#0869e1",
        "--chrome-ink": "#191f28",
        "--chrome-ink-2": "#545c6d",
        "--chrome-line": "#eceff5",
        "--chrome-line-strong": "#d8dde8",
        "--chrome-muted": "#697183",
        "--chrome-ok": "#17834d",
        "--chrome-ok-soft": "#e9f4ee",
        "--chrome-overlay": "rgb(255 255 255 / 0.94)",
        "--chrome-scrim": "rgb(15 19 26 / 0.38)",
        "--chrome-selection-fill": "rgb(8 105 225 / 0.14)",
        "--chrome-selection-stroke": "#0869e1",
        "--chrome-surface": "#ffffff",
        "--chrome-surface-2": "#f9fbfc",
        "--chrome-surface-3": "#e9ecf2",
        "--chrome-tooltip-bg": "#191f28",
        "--chrome-tooltip-ink": "#f9fbfc",
        "--chrome-warn": "#b87409",
        "--chrome-warn-soft": "#fdf3e2",
        "--color-accent": "#0869e1",
        "--color-accent-hover": "#0a5cc4",
        "--color-accent-ink": "#ffffff",
        "--color-accent-soft": "#eef5fe",
        "--color-accent-track": "#e6eff8",
        "--color-azure-100": "#e6eff8",
        "--color-azure-200": "#c9e0fb",
        "--color-azure-50": "#eef5fe",
        "--color-azure-500": "#0869e1",
        "--color-azure-600": "#0a5cc4",
        "--color-azure-700": "#0b4da4",
        "--color-black": "#1a1a1a",
        "--color-canvas": "#ffffff",
        "--color-canvas-grid": "#ebebeb",
        "--color-canvas-ink": "#1a1a1a",
        "--color-canvas-ink-2": "#3a3a3a",
        "--color-canvas-line": "#dcdcdc",
        "--color-canvas-line-strong": "#bfbfbf",
        "--color-canvas-muted": "#6b6b6b",
        "--color-canvas-surface": "#fafafa",
        "--color-chrome": "#eff1f7",
        "--color-cool-0": "#ffffff",
        "--color-cool-100": "#eff1f7",
        "--color-cool-150": "#e9ecf2",
        "--color-cool-200": "#eceff5",
        "--color-cool-25": "#f9fbfc",
        "--color-cool-300": "#d8dde8",
        "--color-cool-400": "#a0a6b4",
        "--color-cool-50": "#f4f6fa",
        "--color-cool-500": "#697183",
        "--color-cool-600": "#545c6d",
        "--color-cool-700": "#3a4150",
        "--color-cool-800": "#262c38",
        "--color-cool-900": "#191f28",
        "--color-cool-950": "#0f131a",
        "--color-current": "currentColor",
        "--color-danger": "#c2410c",
        "--color-danger-soft": "#fbeae3",
        "--color-disabled": "#a0a6b4",
        "--color-focus": "#0869e1",
        "--color-ink": "#191f28",
        "--color-ink-2": "#545c6d",
        "--color-line": "#eceff5",
        "--color-line-strong": "#d8dde8",
        "--color-mono-0": "#ffffff",
        "--color-mono-100": "#f4f4f5",
        "--color-mono-200": "#e4e4e7",
        "--color-mono-300": "#d4d4d8",
        "--color-mono-400": "#a1a1aa",
        "--color-mono-50": "#fafafa",
        "--color-mono-500": "#71717a",
        "--color-mono-600": "#52525b",
        "--color-mono-700": "#3f3f46",
        "--color-mono-800": "#27272a",
        "--color-mono-900": "#18181b",
        "--color-mono-950": "#09090b",
        "--color-muted": "#697183",
        "--color-ok": "#17834d",
        "--color-ok-soft": "#e9f4ee",
        "--color-overlay": "rgb(255 255 255 / 0.94)",
        "--color-scrim": "rgb(15 19 26 / 0.38)",
        "--color-selection-fill": "rgb(8 105 225 / 0.14)",
        "--color-selection-stroke": "#0869e1",
        "--color-surface": "#ffffff",
        "--color-surface-2": "#f9fbfc",
        "--color-surface-3": "#e9ecf2",
        "--color-tooltip": "#191f28",
        "--color-tooltip-ink": "#f9fbfc",
        "--color-transparent": "transparent",
        "--color-warn": "#b87409",
        "--color-warn-soft": "#fdf3e2",
        "--color-white": "#ffffff",
        "--danger": "#c2410c",
        "--danger-pale": "#fbeae3",
        "--dark": "#2a2a2a",
        "--ease-out-quick": "cubic-bezier(0.22, 0.8, 0.3, 1)",
        "--font-mono": ""Geist Mono", ui-monospace, "SF Mono", "JetBrains Mono", Menlo, Consolas, monospace",
        "--font-sans": ""Instrument Sans", "Noto Sans KR", Pretendard, "Apple SD Gothic Neo", system-ui, -apple-system, sans-serif",
        "--gap": "1px",
        "--height-ctl": "36px",
        "--height-ctl-lg": "44px",
        "--height-ctl-sm": "30px",
        "--ink": "#1a1a1a",
        "--ink-2": "#3a3a3a",
        "--inspect-w": "340px",
        "--light": "#d5d5d5",
        "--line": "#dcdcdc",
        "--line-strong": "#bfbfbf",
        "--mid": "#6b6b6b",
        "--mono": "ui-monospace, "SF Mono", "JetBrains Mono", Menlo, Consolas, monospace",
        "--motion-collapse-duration": "200ms",
        "--motion-collapse-easing": "cubic-bezier(0.22, 0.8, 0.3, 1)",
        "--muted": "#6b6b6b",
        "--offwhite": "#f4f4f4",
        "--ok": "#17834d",
        "--ok-pale": "#e9f4ee",
        "--pale": "#ebebeb",
        "--panel-w": "300px",
        "--radius-card": "12px",
        "--radius-chip": "6px",
        "--radius-control": "8px",
        "--radius-float": "12px",
        "--radius-full": "9999px",
        "--radius-modal": "16px",
        "--radius-none": "0",
        "--sans": ""Noto Sans KR", Pretendard, "Apple SD Gothic Neo", system-ui, -apple-system, sans-serif",
        "--shadow-card": "0 1px 2px rgb(25 31 40 / 0.04), 0 4px 12px rgb(25 31 40 / 0.05)",
        "--shadow-chip": "0 1px 2px rgb(25 31 40 / 0.05)",
        "--shadow-modal": "0 8px 20px rgb(25 31 40 / 0.10), 0 28px 64px rgb(25 31 40 / 0.16), 0 0 0 1px rgb(25 31 40 / 0.05)",
        "--shadow-none": "none",
        "--shadow-pop": "0 2px 6px rgb(25 31 40 / 0.06), 0 12px 28px rgb(25 31 40 / 0.10), 0 0 0 1px rgb(25 31 40 / 0.05)",
        "--silver": "#ababab",
        "--size-gap": "12px",
        "--size-rail": "64px",
        "--spacing": "4px",
        "--steel": "#8a8a8a",
        "--surface": "#ffffff",
        "--surface-2": "#fafafa",
        "--text-body": "13px",
        "--text-body--line-height": "1.55",
        "--text-control": "13.5px",
        "--text-control--line-height": "1.4",
        "--text-display": "26px",
        "--text-display--line-height": "1.16",
        "--text-label": "11px",
        "--text-label--line-height": "1.45",
        "--text-micro": "10px",
        "--text-micro--line-height": "1.4",
        "--text-readout": "22px",
        "--text-readout--line-height": "1.2",
        "--text-title": "15px",
        "--text-title--line-height": "1.4",
        "--topbar-h": "56px",
        "--tracking-caps": "0.09em",
        "--warn": "#b87409",
        "--warn-pale": "#fdf3e2",
        "--white": "#ffffff",
      }
    `);
  });

  it("다크 — 라이트와 다른 항목", () => {
    expect(dark).toMatchInlineSnapshot(`
      {
        "--chrome-accent": "#4d9bff",
        "--chrome-accent-hover": "#6fb0ff",
        "--chrome-accent-ink": "#061018",
        "--chrome-accent-soft": "#14243a",
        "--chrome-accent-track": "#1a2b42",
        "--chrome-bg": "#0e1116",
        "--chrome-danger": "#e2764d",
        "--chrome-danger-soft": "#2b1913",
        "--chrome-disabled": "#5b6474",
        "--chrome-focus": "#6fb0ff",
        "--chrome-ink": "#eaedf3",
        "--chrome-ink-2": "#b3bac6",
        "--chrome-line": "#242a34",
        "--chrome-line-strong": "#333b48",
        "--chrome-muted": "#8a93a3",
        "--chrome-ok": "#4cb37e",
        "--chrome-ok-soft": "#12261c",
        "--chrome-overlay": "rgb(22 26 33 / 0.94)",
        "--chrome-scrim": "rgb(0 0 0 / 0.60)",
        "--chrome-selection-fill": "rgb(77 155 255 / 0.20)",
        "--chrome-selection-stroke": "#4d9bff",
        "--chrome-surface": "#161a21",
        "--chrome-surface-2": "#1c212a",
        "--chrome-surface-3": "#252b36",
        "--chrome-tooltip-bg": "#eaedf3",
        "--chrome-tooltip-ink": "#0e1116",
        "--chrome-warn": "#d99c3d",
        "--chrome-warn-soft": "#2a2113",
        "--color-accent": "#4d9bff",
        "--color-accent-hover": "#6fb0ff",
        "--color-accent-ink": "#061018",
        "--color-accent-soft": "#14243a",
        "--color-accent-track": "#1a2b42",
        "--color-chrome": "#0e1116",
        "--color-danger": "#e2764d",
        "--color-danger-soft": "#2b1913",
        "--color-disabled": "#5b6474",
        "--color-focus": "#6fb0ff",
        "--color-ink": "#eaedf3",
        "--color-ink-2": "#b3bac6",
        "--color-line": "#242a34",
        "--color-line-strong": "#333b48",
        "--color-muted": "#8a93a3",
        "--color-ok": "#4cb37e",
        "--color-ok-soft": "#12261c",
        "--color-overlay": "rgb(22 26 33 / 0.94)",
        "--color-scrim": "rgb(0 0 0 / 0.60)",
        "--color-selection-fill": "rgb(77 155 255 / 0.20)",
        "--color-selection-stroke": "#4d9bff",
        "--color-surface": "#161a21",
        "--color-surface-2": "#1c212a",
        "--color-surface-3": "#252b36",
        "--color-tooltip": "#eaedf3",
        "--color-tooltip-ink": "#0e1116",
        "--color-warn": "#d99c3d",
        "--color-warn-soft": "#2a2113",
      }
    `);
  });
});
